
dataWriter:
  bootstrapServers: "localhost:9092"
  producerName: "server1"
  writerTopicName: "documents"
elasticConfiguration:
    transportAddresses:
        - address: "localhost"
          port: 9300
